### ISSUE TITLE
All examples workloads are failing with latest gramine master 

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/examples#103]
All the workloads are failing with latest gramine master because of Gramine Commit [[PAL] Validate entrypoint ELF file separately](https://github.com/gramineproject/gramine/commit/72668bb391d9a311148d8e824fb006f314e8dbba), While generating sgx manifest build is getting failed with tomli-TOMLDecodeError because it adds a new line in manifest file
```
 **WARNING: `loader.entrypoint = "file:..."` manifest syntax is deprecated, please switch to `loader.entrypoint.uri = "file:..."`**
```

**Error:**
**curl.manifest**
```
[sgx.cpu_features]
avx = "unspecified"
avx512 = "unspecified"
amx = "unspecified"
mpx = "disabled"
pkru = "disabled"
WARNING: `loader.entrypoint = "file:..."` manifest syntax is deprecated, please switch to `loader.entrypoint.uri = "file:..."`
```

**StackTrace**
```
Traceback (most recent call last):
  File "/home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel9_server_6.7/gramine/usr/bin/gramine-sgx-sign", line 174, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel9_server_6.7/gramine/usr/bin/gramine-sgx-sign", line 130, in main
    manifest = Manifest.load(manifest_file)
  File "/home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel9_server_6.7/gramine/usr/lib64/python3.9/site-packages/graminelibos/manifest.py", line 395, in load
    return cls.loads(f.read())
  File "/home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel9_server_6.7/gramine/usr/lib64/python3.9/site-packages/graminelibos/manifest.py", line 391, in loads
    return cls(s)
  File "/home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel9_server_6.7/gramine/usr/lib64/python3.9/site-packages/graminelibos/manifest.py", line 300, in __init__
    manifest = tomli.loads(manifest_str)
  File "/usr/local/lib/python3.9/site-packages/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/usr/local/lib/python3.9/site-packages/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/usr/local/lib/python3.9/site-packages/tomli/_parser.py", line 366, in parse_key_value_pair
    raise suffixed_err(src, pos, "Expected '=' after a key in a key/value pair")
tomli.TOMLDecodeError: Expected '=' after a key in a key/value pair (at line 81, column 8)
make: *** [Makefile:37: sgx_sign] Error 1
```

I tried with PR https://github.com/gramineproject/examples/pull/99 and this seems to fix the issue

**Comment by dimakuv** [comment]
@anjalirai-intel Thanks for noticing this!

That was such a blooper on my side... I didn't test that commit/PR with any non-affected examples. Thanks for catching this.

The fix is here: https://github.com/gramineproject/gramine/pull/1953
